#%RAML 1.0 NamedExample
{
  "sourceSystemInfo": [
    {
      "sourceSystemId": "SFDC",
      "sourceSystemPartyId": "20999"
    }
  ],
  "person": {
    "firstName": "STEVEN",
    "lastName": "DODDS",
    "salutation": "Mr.",
    "suffix": "Sr.",
    "preferredName": "NA",
    "middleName": "JAMES"
  },
  "contactMethod": [
    {
      "contactMethodIsPrimary": "Y",
      "contactMethodValueExtension": "1234",
      "contactMethodValue": "2345678901",
      "contactMethodType": "Cell"
    }
  ],
  "personAddress": [
    {
      "address": {
        "territory": "OH",
        "addressLine1": "43",
        "addressLine2": "Broadmead Village",
        "addressLine3": "CONISTON ROAD",
        "country": "US",
        "postalCode": "12345",
        "city": "FOLKESTONE"
      },
      "addressType": "HOM"
    }
  ],
  "personAssociation": [
    {
      "personAssociationType": "Spouse",
      "associatedPersonId": "2",
      "partyRoleType": "test"
    }
  ],
  "personRole": {
    "personRoleType": [
      "PREP"
      ]
  },
  "identification": [
    {
      "issuingId": "DEA",
      "identificationType": "Passport",
      "identificationEndDt": "2025-01-27",
      "identificationCategory": "Passport Number",
      "identificationNum": "abc1234",
      "identificationStartDt": "2020-01-27"
    },
    {
      "issuingId": "DEA",
      "identificationType": "Passport",
      "identificationEndDt": "2025-01-27",
      "identificationCategory": "Passport Number",
      "identificationNum": "abc1234",
      "identificationStartDt": "2020-01-27"
    }
  ],
  "personPreference": [
    {
      "personPreferenceType": "MKTG",
      "personPreferenceSubType": "Email"
    }
  ]
}