#%RAML 1.0 NamedExample
{
  "id": "20085",
  "sourceSystemInfo": [
    {
      "sourceSystemId": "SV2",
      "sourceSystemPartyId": "4197"
    }
  ],
  "person": {
    "firstName": "STEVEN",
    "lastName": "DODDS",
    "salutation": "Mr.",
    "suffix": "Sr.",
    "preferredName": "NA",
    "middleName": "JAMES"
  },
  "personAddress": [
    {
      "address": {
        "territory": "OH",
        "addressLine1": "43",
        "addressLine2": "Broadmead Village",
        "addressLine3": "CONISTON ROAD",
        "country": "US",
        "postalCode": "12345",
        "city": "FOLKESTONE"
      },
      "addressType": "HOM"
    }
  ]
}