#%RAML 1.0 NamedExample

{
  "errors": [
    {
      "status": "403",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "Access to the requested resource was denied",
      "detail": "Access to the requested resource was denied",
      "correlationId": "dd960082-abbf-47c2-8c65-f18eeb35848b"
    }
  ]
}
