#%RAML 1.0 NamedExample

{
  "errors": [
    {
      "status": "405",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "The target resource does not support the requested method",
      "detail": "The target resource does not support the requested method",
      "correlationId": "dd960082-abbf-47c2-8c65-f18eeb35848b"
    }
  ]
}
