#%RAML 1.0 NamedExample

{
  "errors": [
    {
      "status": "501",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "Not Implemented",
      "detail": "Not Implemented",
      "correlationId": "dd960082-abbf-47c2-8c65-f18eeb35848b"
    }
  ]
}
