#%RAML 1.0 NamedExample

{
  "errors": [
    {
      "status": "415",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "The server is refusing to the request because it is not in a format supported by the target resource.",
      "detail": "The server is refusing to the request because it is not in a format supported by the target resource.",
      "correlationId": "dd960082-abbf-47c2-8c65-f18eeb35848b"
    }
  ]
}
