#%RAML 1.0 NamedExample

{
  "errors": [
    {
      "status": "429",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "The server is refusing to handle the request because a rate limit has been exceeded.",
      "detail": "The server is refusing to handle the request because a rate limit has been exceeded.",
      "correlationId": "dd960082-abbf-47c2-8c65-f18eeb35848b"
    }
  ]
}
