#%RAML 1.0 NamedExample

{
  "errors": [
    {
      "status": "500",
      "source": { "pointer": "/data/attributes/firstName" },
      "title":  "The server was unable to process the request due to an internal error",
      "detail": "The server was unable to process the request due to an internal error",
      "correlationId": "dd960082-abbf-47c2-8c65-f18eeb35848b"
    }
  ]
}
